/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false src/worker-configuration.d.ts` (hash: f506f6abb67177f7e9436150d9e1bb25)
interface __BaseEnv_Env {
	PUBLIC_POSTHOG_UI_HOST: "https://eu.posthog.com";
	PUBLIC_POSTHOG_PROJECT_TOKEN: string;
	PUBLIC_POSTHOG_HOST: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
