/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=wrangler-types.env --include-runtime=false src/worker-configuration.d.ts` (hash: d1120ad4c554b31118d88e897ce718ec)
interface __BaseEnv_Env {
	PUBLIC_POSTHOG_PROJECT_TOKEN: "phc_AjhL5JJU9TGMCGnMkDKSs9kprYPsRhr6WfxQwJZA5KNf";
	PUBLIC_POSTHOG_HOST: "https://t.itsjan.dev";
	PUBLIC_POSTHOG_UI_HOST: "https://eu.posthog.com";
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
declare module "*.txt" {
	const value: string;
	export default value;
}
declare module "*.html" {
	const value: string;
	export default value;
}
declare module "*.sql" {
	const value: string;
	export default value;
}
declare module "*.bin" {
	const value: ArrayBuffer;
	export default value;
}
declare module "*.wasm" {
	const value: WebAssembly.Module;
	export default value;
}
declare module "*.wasm?module" {
	const value: WebAssembly.Module;
	export default value;
}