/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=wrangler-types.env --include-runtime=false src/worker-configuration.d.ts` (hash: 21955e1928be2769f7526863195c79fc)
interface __BaseEnv_Env {
	PUBLIC_POSTHOG_PROJECT_TOKEN: "phc_AjhL5JJU9TGMCGnMkDKSs9kprYPsRhr6WfxQwJZA5KNf";
	PUBLIC_POSTHOG_HOST: "https://t.itsjan.dev";
	PUBLIC_POSTHOG_UI_HOST: "https://eu.posthog.com";
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
